#!/bin/bash
#SBATCH -p medium
#SBATCH -t 48:00:00
#SBATCH -J GWAS
#SBATCH -c 4
#SBATCH -N 1
#SBATCH --mem=200G
#SBATCH -o 2025_03_06_GWAS_with_PLINK_all_traits_MAF_Mind_with_perm_envPC_2020_2021_2022.out
#SBATCH -e 2025_03_06_GWAS_with_PLINK_all_traits_MAF_Mind_with_perm_envPC_2020_2021_2022.err

module load rev/20.12
module load rev/21.12
module load plink/1.90
# SD
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_SD.txt --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/SD_MAFMindfilt
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_SD.txt --aperm 10 1000000 0.0001 0.01 5 0.001 --perm --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/SD_MAFMindfilt_perm
# D13_2020
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2,EnvPC1_2020 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_D13_2020.txt --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/D13_2020_MAFMindfilt_weather_data_2020_2021_2022_noSept
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2,EnvPC1_2020 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_D13_2020.txt --aperm 10 1000000 0.0001 0.01 5 0.001 --perm --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/D13_2020_MAFMindfilt_weather_data_2020_2021_2022_noSept_perm
# D13_2021
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2,EnvPC1_2021 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_D13_2021.txt --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/D13_2021_MAFMindfilt_weather_data_2020_2021_2022_noSept
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2,EnvPC1_2021 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_D13_2021.txt --aperm 10 1000000 0.0001 0.01 5 0.001 --perm --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/D13_2021_MAFMindfilt_weather_data_2020_2021_2022_noSept_perm
# D13_2022
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2,EnvPC1_2022 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_D13_2022.txt --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/D13_2022_MAFMindfilt_weather_data_2020_2021_2022_noSept
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2,EnvPC1_2022 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_D13_2022.txt --aperm 10 1000000 0.0001 0.01 5 0.001 --perm --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/D13_2022_MAFMindfilt_weather_data_2020_2021_2022_noSept_perm
# NC_2020
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_NC_2020.txt --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/NC_2020_MAFMindfilt_weather_data_2020_2021_2022_noSept
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_NC_2020.txt --aperm 10 1000000 0.0001 0.01 5 0.001 --perm --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/NC_2020_MAFMindfilt
# NC_2021
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_NC_2021.txt --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/NC_2021_MAFMindfilt_weather_data_2020_2021_2022_noSept
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_NC_2021.txt --aperm 10 1000000 0.0001 0.01 5 0.001 --perm --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/NC_2021_MAFMindfilt
# NC_2022
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_NC_2022.txt --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/NC_2022_MAFMindfilt_weather_data_2020_2021_2022_noSept
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_NC_2022.txt --aperm 10 1000000 0.0001 0.01 5 0.001 --perm --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/NC_2022_MAFMindfilt
# CNR_2020
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_CNR_2020.txt --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/CNR_2020_MAFMindfilt_weather_data_2020_2021_2022_noSept
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_CNR_2020.txt --aperm 10 1000000 0.0001 0.01 5 0.001 --perm --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/CNR_2020_MAFMindfilt
# CNR_2021
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_CNR_2021.txt --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/CNR_2021_MAFMindfilt_weather_data_2020_2021_2022_noSept
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_CNR_2021.txt --aperm 10 1000000 0.0001 0.01 5 0.001 --perm --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/CNR_2021_MAFMindfilt
# CNR_2022
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_CNR_2022.txt --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/CNR_2022_MAFMindfilt_weather_data_2020_2021_2022_noSept
plink --bfile /Beech_project/Romanian_Beech_Data/Genotypic_data/2024_RoBe_all_bed_format --linear genotypic --allow-no-sex --maf 0.005 --mind 1 --remove list_individuals_remove.txt --covar /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/covar_env_PCs_weather_dt.txt --covar-name spet_PC1,spet_PC2 --pheno /Beech_project/Romanian_Beech_Data/GWAS/PLINK/input_dir/RoBe_CNR_2022.txt --aperm 10 1000000 0.0001 0.01 5 0.001 --perm --out /Beech_project/Romanian_Beech_Data/GWAS/PLINK/Results/CNR_2022_MAFMindfilt
